version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672     # AMQP protocol port
      - 15672:15672   # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - url-encoder-network
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq

  url-encoder:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672/
      - WEB_HOST=http://localhost:5173
      - SERVER_PORT=3333
    depends_on:
      - rabbitmq
    networks:
      - url-encoder-network
  
networks:
  url-encoder-network:
    name: url-encoder-network

volumes:
  rabbitmq-data:
  rabbitmq-log: