version: '3.8'
services:
  url-encoder:
    image: golang:1.19.4-alpine3.17
    ports:
      - 3333:3333
    working_dir: /go/src/github.com/guilhermesalviano/url-encoder
    volumes:
      - ./:/go/src/github.com/guilhermesalviano/url-encoder
    command: sh -c "apk add --no-cache git make && git config --global --add url.'git@github.com:'.insteadOf 'https://github.com/' && make deps && make run"
    networks:
      - url-encoder-network
  #build:
  #  image: golang:1.19.4-alpine3.17
  #  env_file: development.env
  #  ports:
  #    - 7020:80
  #  volumes:
  #    - ./:/go/src/github.com/guilhermesalviano/url-encoder
  #  working_dir: /go/src/github.com/guilhermesalviano/url-encoder
  #  command: sh -c "git config --global --add url.'git@github.com:'.insteadOf #'https://github.com/' && make deps && make build"
  #  networks:
  #    - network
  #  environment:
  #    - GO111MODULE=on
  #    - GOSUMDB=off
  #    - GOPROXY=direct
  #unit-test:
  #  image: golang:1.19.4-alpine3.17
  #  volumes:
  #    - ./:/go/src/github.com/guilhermesalviano/url-encoder
  #  working_dir: /go/src/github.com/guilhermesalviano/url-encoder
  #  command:   sh -c "git config --global --add url.'git@github.com:'.#insteadOf 'https://github.com/' && make test"
  #  environment:
  #      - GO111MODULE=on
  #      - GOSUMDB=off
  #      - GOPROXY=direct
  #vendor:
  #  image: golang:1.19.4-alpine3.17
  #  volumes:
  #    - ./:/go/src/github.com/guilhermesalviano/url-encoder
  #  working_dir: /go/src/github.com/guilhermesalviano/url-encoder
  #  environment:
  #    - DEPNOLOCK=1
  #    - GO111MODULE=on
  #    - GOSUMDB=off
  #    - GOPROXY=direct
  #  command:  sh -c "git config --global --add url.'git@github.com:'.insteadOf 'https://github.com/' && make deps"
  
networks:
  url-encoder-network:
    name: url-encoder-network