name = "url-encoder"
compatibility_date = "2024-02-12"
main = "./build/server/index.js"

[site]
bucket = "./build/client"

[build]
command = "npm run build"  # Ensure this matches your Remix build command
[build.upload]
format = "service-worker"